### ISSUE TITLE
smart_filter.py depends on Python 3 but Hexchat .debs are all built with Python 2

### ISSUE THREAD

**Issue by sbts** [FichteFoll/hexchat-addons#1]
There is not a lot of point making these addons only work with Python 3 until all common distros have python 3 build into Hexchat.
Debian Stable, Linux Mint, Ubuntu don't so the addon is broken for them.

I managed to hack most of the script into submission but was still getting an error at line 40 during runtime.
I've found a perl solution to my needs that worked out of the box, but I would like to be able to use this addon (smart_filter.py) in the future.

**Comment by FichteFoll** [comment]
Thanks for the heads up. I only use Python 3, which is why I didn't pay much attention to Py2-compatibility. I didn't know that most Linux distros' .debs are built with Py2, which is a bummer.

I'll see what I can do (in the near future).

**Comment by sbts** [comment]
```
No Problem,

It just surprised me and took a bit of asking about on #hexchat and
#python to work out why it didn't load :-)

I managed to get it to load with a few modifications, in particular
getting rid of super()
but still had issues during runtime around line 40 in my slightly
modified version. (probably the same line)in the original version)

If you want a copy of what I ended up with, let me know.

On 29/02/16 04:01, FichteFoll wrote:


  Thanks for the heads up. I only use Python 3, which is why I
    didn't pay much attention to Py2-compatibility. I didn't know
    that most Linux distros' .debs are built with Py2, which is a
    bummer.
  I'll see what I can do (in the near future).
  —
    Reply to this email directly or view
      it on GitHub.
```
